version: "3.5"
services:
  postgres:
    image: postgres:11.2-alpine
    container_name: meta-extractor-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/1-init.sql:rw
